import React from 'react';
import './Projects.css';

const Projects = () => {
    const projectList = [
        {
            title: "The Intelligence Hub API",
            description: "A single API to simplify and expedite AI app development, providing interoperability between LLM hosts, RAG dbs, image models, and more.",
            githubLink: "https://github.com/AppliedAI-Org/IntelligenceHub.git",
            liveLink: "https://appliedai-org.github.io/homepage/"
        },
        {
            title: "NLSequel",
            description: "A natural language to SQL conversion tool with a simple API and even more straight forward pay-as-you-go pricing.",
            githubLink: "https://github.com/jacob-j-thomas/conversationalaiwebsite",
            liveLink: "https://nlsequel.azurewebsites.net"
        },
        {
            title: "Binary Sentiment Analysis with ML",
            description: "A binary sentiment analysis project written without utilizing any existing packages, with the goal of fully understanding LLM architecture and the underlying math that make them possible.",
            githubLink: "https://github.com/Jacob-J-Thomas/Binary-Sentiment-Analysis-with-Machine-Learning"
        },
        {
            title: "DarkSheet",
            description: "A chrome extension for the spreadsheet app, Smartsheets, that inverts the color scheme, which currently has over 1k active users.",
            githubLink: "https://github.com/Jacob-J-Thomas/Dark-Mode-Chrome-Extension",
            liveLink: "https://chromewebstore.google.com/detail/darksheet/banmhmlpididlolbalhnngfhgcahefdb?hl=en"
        },
        {
            title: "AI Text Adventure (Coming Soon!)",
            description: "A text adventure game with endless possibilities, all generated by LLMs via carefully orchestrated prompting.",
            githubLink: "https://github.com/Jacob-J-Thomas/ConversationalAIWebsite"
        },
        {
            title: "One Shot (Coming Soon!)",
            description: "An AI headshot, portrait, and photo editing app with an affinity for simplicity and affordability.",
            githubLink: "https://github.com/example/project-three"
        }
    ];

    return (
        <div className="projects-container">
            <h1 className="projects-title">Projects</h1>
            <div className="projects-list-container">
                <div className="projects-list">
                    {projectList.map((project, index) => (
                        <div key={index} className="project-card">
                            <h2 className="project-title">{project.title}</h2>
                            <p className="project-description">{project.description}</p>
                            <div className="project-links">
                                {project.githubLink && (
                                    <a href={project.githubLink} target="_blank" rel="noopener noreferrer" className="project-link">
                                        GitHub
                                    </a>
                                )}
                                {project.liveLink && (
                                    <a href={project.liveLink} target="_blank" rel="noopener noreferrer" className="project-link">
                                        Live Site
                                    </a>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default Projects;
